FROM python:3.7.3

WORKDIR /app

COPY requirements.txt .
COPY loader.py /app/
RUN grep -v 'dotenv' requirements.txt > requirements_exclude.txt
RUN pip install -r requirements_exclude.txt

ENTRYPOINT [ "pylint" ]

CMD [ "loader.py" ]